apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: certservice
  namespace: family
  labels:
    app: certservice
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: certservice