apiVersion: v1
kind: Service
metadata:
  name: certservice
  namespace: family
  labels:
    app: certservice
spec:
  type: ClusterIP
  ports:
   - port: 8080
     name: certservice
  selector:
   app: certservice
